{
 "title": "New Dashboard Anomali Transaksi ATM(On Process)",
 "description": "Final Project",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#03ada8;\"><b><font size=\"15\" color=\"#FFFFFF\">Fitur [BRI] Cash Withdrawal</font></b></p>\n</CENTER>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#32D218;\"><b><font size=\"8\" color=\"#000000\">Trx [BRI] Cash Withdrawal Success</font></b></p>\n</CENTER>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "TOTAL TRX [BRI] CASH WITHDRAWAL TRX SUCCESS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "\nDECLARE @fitur VARCHAR(50)\nDECLARE @isocode VARCHAR(50)\nDECLARE @is_success VARCHAR(20)\nDECLARE @max_date datetime\nDECLARE @yesterday_date datetime\nDECLARE @total_in_summary_daily INT\nDECLARE @total_in_summary_h1 INT\nDECLARE @backdate_days_interval int\n\nset @backdate_days_interval = 7\nselect @yesterday_date  = convert(varchar(10),getdate()-1,120)\nselect @total_in_summary_daily =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\nselect @total_in_summary_h1 =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_H1 where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\n--select @total_in_summary_daily,@total_in_summary_h1\nset @max_date = convert(datetime,\n CONVERT(VARCHAR(14),getdate(),120) \n\t\t+  RIGHT('00'+ CONVERT(varchar(2), (DATEPART(minute,getdate()) / 30) * 30),2) + ':00',120)\nSET @fitur = '[BRI] CASH WITHDRAWAL'\nSET @is_success = 'sukses'\nset @isocode = '210'\n\n\n\nIF @total_in_summary_daily > 0 \nBEGIN\n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_trx' metric, total_trx num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, total_trx num from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t), combine as (\n\tselect  DATEADD(HOUR, -7, trx_date) trx_date,metric,num from ori_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date\nEND\nELSE \nBEGIN \n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_trx' metric, total_trx num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, total_trx num from PROSWITCHING.dbo.atm_transaction_summary_daily_H1\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, total_trx num from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\t), combine as (\n\tselect  DATEADD(HOUR, -7, trx_date) trx_date,metric,num from ori_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date,metric\nEND \n\n"
    },
    {
     "rawSql": "\nDECLARE @fitur VARCHAR(50)\nDECLARE @isocode VARCHAR(50)\nDECLARE @is_success VARCHAR(20)\nDECLARE @max_date datetime\nDECLARE @yesterday_date datetime\nDECLARE @total_in_summary_daily INT\nDECLARE @total_in_summary_h1 INT\nDECLARE @backdate_days_interval int\n\nset @backdate_days_interval = 7\nselect @yesterday_date  = convert(varchar(10),getdate()-1,120)\nselect @total_in_summary_daily =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\nselect @total_in_summary_h1 =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_H1 where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\n--select @total_in_summary_daily,@total_in_summary_h1\nset @max_date = convert(datetime,\n CONVERT(VARCHAR(14),getdate(),120) \n\t\t+  RIGHT('00'+ CONVERT(varchar(2), (DATEPART(minute,getdate()) / 30) * 30),2) + ':00',120)\nSET @fitur = '[BRI] CASH WITHDRAWAL'\nSET @is_success = 'sukses'\nset @isocode = '210'\n\n\n\nIF @total_in_summary_daily > 0 \nBEGIN\n\twith pred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_trx' metric, total_trx num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t), combine as (\n\tselect DATEADD(HOUR, -7, trx_date) trx_date,metric,num from pred_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date\nEND\nELSE \nBEGIN \n    with pred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_trx' metric, total_trx num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t), combine as (\n\tselect DATEADD(HOUR, -7, trx_date) trx_date,metric,num from pred_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date,metric\nEND \n\n"
    }
   ]
  },
  {
   "title": "TOTAL AMOUNT [BRI] CASH WITHDRAWAL TRX SUCCESS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "DECLARE @fitur VARCHAR(50)\nDECLARE @isocode VARCHAR(50)\nDECLARE @is_success VARCHAR(20)\nDECLARE @max_date datetime\nDECLARE @yesterday_date datetime\nDECLARE @total_in_summary_daily INT\nDECLARE @total_in_summary_h1 INT\nDECLARE @backdate_days_interval int\n\nset @backdate_days_interval = 7\nselect @yesterday_date  = convert(varchar(10),getdate()-1,120)\nselect @total_in_summary_daily =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\nselect @total_in_summary_h1 =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_H1 where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\n--select @total_in_summary_daily,@total_in_summary_h1\nset @max_date = convert(datetime,\n CONVERT(VARCHAR(14),getdate(),120) \n\t\t+  RIGHT('00'+ CONVERT(varchar(2), (DATEPART(minute,getdate()) / 30) * 30),2) + ':00',120)\nSET @fitur = '[BRI] CASH WITHDRAWAL'\nSET @is_success = 'sukses'\nset @isocode = '210'\n\n\nIF @total_in_summary_daily > 0 \nBEGIN\n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_amount' metric, total_amount num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tunion all \n\tSELECT  trx_date,'ori_total_amount' metric, total_amount num  FROM PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t), combine as (\n\tselect  DATEADD(HOUR, -7, trx_date) trx_date,metric,num from ori_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date\nEND\nELSE \nBEGIN \n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_amount' metric, total_amount num FROM  PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tunion all \n\tSELECT  trx_date,'ori_total_amount' metric, total_amount num from PROSWITCHING.dbo.atm_transaction_summary_daily_H1\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\tunion all \n\tSELECT  trx_date,'ori_total_amount' metric, total_amount num from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\t), combine as (\n\tselect  DATEADD(HOUR, -7, trx_date) trx_date,metric,num from ori_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date\nEND \n\n"
    },
    {
     "rawSql": "DECLARE @fitur VARCHAR(50)\nDECLARE @isocode VARCHAR(50)\nDECLARE @is_success VARCHAR(20)\nDECLARE @max_date datetime\nDECLARE @yesterday_date datetime\nDECLARE @total_in_summary_daily INT\nDECLARE @total_in_summary_h1 INT\nDECLARE @backdate_days_interval int\n\nset @backdate_days_interval = 7\nselect @yesterday_date  = convert(varchar(10),getdate()-1,120)\nselect @total_in_summary_daily =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\nselect @total_in_summary_h1 =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_H1 where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\n--select @total_in_summary_daily,@total_in_summary_h1\nset @max_date = convert(datetime,\n CONVERT(VARCHAR(14),getdate(),120) \n\t\t+  RIGHT('00'+ CONVERT(varchar(2), (DATEPART(minute,getdate()) / 30) * 30),2) + ':00',120)\nSET @fitur = '[BRI] CASH WITHDRAWAL'\nSET @is_success = 'sukses'\nset @isocode = '210'\n\n\nIF @total_in_summary_daily > 0 \nBEGIN\n\twith pred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_amount' metric, total_amount num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t), combine as (\n\tselect DATEADD(HOUR, -7, trx_date) trx_date,metric,num from pred_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date\nEND\nELSE \nBEGIN \n\twith pred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_amount' metric, total_amount num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t), combine as (\n\tselect DATEADD(HOUR, -7, trx_date) trx_date,metric,num from pred_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date\nEND \n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#FFF701;\"><b><font size=\"15\" color=\"#000000\">Trx [BRI] CASH WITHDRAWAL Fail Customer</font></b></p>\n</CENTER>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "TOTAL TRX [BRI] CASH WITHDRAWAL TRX GAGAL BISNIS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "\nDECLARE @fitur VARCHAR(50)\nDECLARE @isocode VARCHAR(50)\nDECLARE @is_success VARCHAR(20)\nDECLARE @max_date datetime\nDECLARE @yesterday_date datetime\nDECLARE @total_in_summary_daily INT\nDECLARE @total_in_summary_h1 INT\nDECLARE @backdate_days_interval int\n\nset @backdate_days_interval = 7\nselect @yesterday_date  = convert(varchar(10),getdate()-1,120)\nselect @total_in_summary_daily =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\nselect @total_in_summary_h1 =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_H1 where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\n--select @total_in_summary_daily,@total_in_summary_h1\nset @max_date = convert(datetime,\n CONVERT(VARCHAR(14),getdate(),120) \n\t\t+  RIGHT('00'+ CONVERT(varchar(2), (DATEPART(minute,getdate()) / 30) * 30),2) + ':00',120)\nSET @fitur = '[BRI] CASH WITHDRAWAL'\nSET @is_success = 'gagal_bisnis'\nset @isocode = '210'\n\n\n\nIF @total_in_summary_daily > 0 \nBEGIN\n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_trx) num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_trx) num  from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and isocode =  @isocode\n\tgroup by trx_date,is_success\n\t),\n\tpred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_trx' metric, sum(total_trx)  num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t\tgroup by trx_date,is_success\n\t), combine as (\n\tselect  DATEADD(HOUR, -7, trx_date) trx_date,metric,num from ori_total_trx\n\tunion all \n\tselect DATEADD(HOUR, -7, trx_date) trx_date,metric,num from pred_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date\nEND\nELSE \nBEGIN \n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_trx)  num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_trx)  num from PROSWITCHING.dbo.atm_transaction_summary_daily_H1\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_trx)  num from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\tgroup by trx_date,is_success\n\t),\n\tpred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_trx' metric, sum(total_trx)  num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t\tgroup by trx_date,is_success\n\t), combine as (\n\tselect  DATEADD(HOUR, -7, trx_date) trx_date,metric,num from ori_total_trx\n\tunion all \n\tselect DATEADD(HOUR, -7, trx_date) trx_date,metric,num from pred_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date,metric\nEND \n\n"
    }
   ]
  },
  {
   "title": "TOTAL AMOUNT [BRI] CASH WITHDRAWAL TRX GAGAL BISNIS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "\nDECLARE @fitur VARCHAR(50)\nDECLARE @isocode VARCHAR(50)\nDECLARE @is_success VARCHAR(20)\nDECLARE @max_date datetime\nDECLARE @yesterday_date datetime\nDECLARE @total_in_summary_daily INT\nDECLARE @total_in_summary_h1 INT\nDECLARE @backdate_days_interval int\n\nset @backdate_days_interval = 7\nselect @yesterday_date  = convert(varchar(10),getdate()-1,120)\nselect @total_in_summary_daily =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\nselect @total_in_summary_h1 =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_H1 where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\n--select @total_in_summary_daily,@total_in_summary_h1\nset @max_date = convert(datetime,\n CONVERT(VARCHAR(14),getdate(),120) \n\t\t+  RIGHT('00'+ CONVERT(varchar(2), (DATEPART(minute,getdate()) / 30) * 30),2) + ':00',120)\nSET @fitur = '[BRI] CASH WITHDRAWAL'\nSET @is_success = 'gagal_bisnis'\nset @isocode = '210'\n\n\n\nIF @total_in_summary_daily > 0 \nBEGIN\n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_amount) num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_amount) num  from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and isocode =  @isocode\n\tgroup by trx_date,is_success\n\t),\n\tpred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_trx' metric, sum(total_amount)  num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t\tgroup by trx_date,is_success\n\t), combine as (\n\tselect  DATEADD(HOUR, -7, trx_date) trx_date,metric,num from ori_total_trx\n\tunion all \n\tselect DATEADD(HOUR, -7, trx_date) trx_date,metric,num from pred_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date\nEND\nELSE \nBEGIN \n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_amount)  num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_amount)  num from PROSWITCHING.dbo.atm_transaction_summary_daily_H1\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_amount)  num from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\tgroup by trx_date,is_success\n\t),\n\tpred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_trx' metric, sum(total_amount)  num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t\tgroup by trx_date,is_success\n\t), combine as (\n\tselect  DATEADD(HOUR, -7, trx_date) trx_date,metric,num from ori_total_trx\n\tunion all \n\tselect DATEADD(HOUR, -7, trx_date) trx_date,metric,num from pred_total_trx\n\t)\n\tselect trx_date as time, metric, num from combine\n\torder by trx_date,metric\nEND \n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "<CENTER>\n<p style=\"background-color:#F90E0E;\"><b><font size=\"15\" color=\"#000000\">Trx [BRI] CASH WITHDRAWAL Fail System</font></b></p>\n</CENTER>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "TOTAL TRX [BRI] CASH WITHDRAWAL TRX GAGAL SISTEM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "\nDECLARE @fitur VARCHAR(50)\nDECLARE @isocode VARCHAR(50)\nDECLARE @is_success VARCHAR(20)\nDECLARE @max_date datetime\nDECLARE @yesterday_date datetime\nDECLARE @total_in_summary_daily INT\nDECLARE @total_in_summary_h1 INT\nDECLARE @backdate_days_interval int\n\nset @backdate_days_interval = 7\nselect @yesterday_date  = convert(varchar(10),getdate()-1,120)\nselect @total_in_summary_daily =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\nselect @total_in_summary_h1 =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_H1 where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\n--select @total_in_summary_daily,@total_in_summary_h1\nset @max_date = convert(datetime,\n CONVERT(VARCHAR(14),getdate(),120) \n\t\t+  RIGHT('00'+ CONVERT(varchar(2), (DATEPART(minute,getdate()) / 30) * 30),2) + ':00',120)\nSET @fitur = '[BRI] CASH WITHDRAWAL'\nSET @is_success = 'gagal_sistem'\nset @isocode = '210'\n\n\n\nIF @total_in_summary_daily > 0 \nBEGIN\n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_trx) num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_trx) num  from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and isocode =  @isocode\n\tgroup by trx_date,is_success\n\t),\n\tpred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_trx' metric, sum(total_trx)  num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t\tgroup by trx_date,is_success\n\t), combine as (\n select  DATEADD(HOUR, -7, trx_date) trx_date,metric, \n    -- Filter nilai negatif menjadi 0\n    CASE \n        WHEN num < 0 THEN 0 \n        ELSE num \n    END AS num\n    from ori_total_trx\n    union all \n    select DATEADD(HOUR, -7, trx_date) trx_date,metric, \n    -- Filter nilai negatif menjadi 0\n    CASE \n        WHEN num < 0 THEN 0 \n        ELSE num \n    END AS num\n    from pred_total_trx\n    )\n    select trx_date as time, metric, num from combine\n    where num > 0\n    order by trx_date\nEND\nELSE \nBEGIN \n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_trx)  num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_trx)  num from PROSWITCHING.dbo.atm_transaction_summary_daily_H1\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_trx)  num from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\tgroup by trx_date,is_success\n\t),\n\tpred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_trx' metric, sum(total_trx)  num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t\tgroup by trx_date,is_success\n\t), combine as (\n select  DATEADD(HOUR, -7, trx_date) trx_date,metric, \n    -- Filter nilai negatif menjadi 0\n    CASE \n        WHEN num < 0 THEN 0 \n        ELSE num \n    END AS num\n    from ori_total_trx\n    union all \n    select DATEADD(HOUR, -7, trx_date) trx_date,metric, \n    -- Filter nilai negatif menjadi 0\n    CASE \n        WHEN num < 0 THEN 0 \n        ELSE num \n    END AS num\n    from pred_total_trx\n    )\n    select trx_date as time, metric, num from combine\n    where num > 0\n    order by trx_date,metric\nEND \n\n"
    }
   ]
  },
  {
   "title": "TOTAL AMOUNT [BRI] CASH WITHDRAWAL TRX GAGAL SISTEM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "\nDECLARE @fitur VARCHAR(50)\nDECLARE @isocode VARCHAR(50)\nDECLARE @is_success VARCHAR(20)\nDECLARE @max_date datetime\nDECLARE @yesterday_date datetime\nDECLARE @total_in_summary_daily INT\nDECLARE @total_in_summary_h1 INT\nDECLARE @backdate_days_interval int\n\nset @backdate_days_interval = 7\nselect @yesterday_date  = convert(varchar(10),getdate()-1,120)\nselect @total_in_summary_daily =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\nselect @total_in_summary_h1 =  count(1) from  PROSWITCHING.dbo.atm_transaction_summary_daily_H1 where convert(varchar(10),trx_date,120) = convert(varchar(10),@yesterday_date,120)\n--select @total_in_summary_daily,@total_in_summary_h1\nset @max_date = convert(datetime,\n CONVERT(VARCHAR(14),getdate(),120) \n\t\t+  RIGHT('00'+ CONVERT(varchar(2), (DATEPART(minute,getdate()) / 30) * 30),2) + ':00',120)\nSET @fitur = '[BRI] CASH WITHDRAWAL'\nSET @is_success = 'gagal_sistem'\nset @isocode = '210'\n\n\n\nIF @total_in_summary_daily > 0 \nBEGIN\n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_amount) num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_amount) num  from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and isocode =  @isocode\n\tgroup by trx_date,is_success\n\t),\n\tpred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_trx' metric, sum(total_amount)  num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t\tgroup by trx_date,is_success\n\t), combine as (\n select  DATEADD(HOUR, -7, trx_date) trx_date,metric, \n    -- Filter nilai negatif menjadi 0\n    CASE \n        WHEN num < 0 THEN 0 \n        ELSE num \n    END AS num\n    from ori_total_trx\n    union all \n    select DATEADD(HOUR, -7, trx_date) trx_date,metric, \n    -- Filter nilai negatif menjadi 0\n    CASE \n        WHEN num < 0 THEN 0 \n        ELSE num \n    END AS num\n    from pred_total_trx\n    )\n    select trx_date as time, metric, num from combine\n    where num > 0\n    order by trx_date\nEND\nELSE \nBEGIN \n\twith ori_total_trx as (\n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_amount)  num FROM PROSWITCHING.dbo.atm_transaction_summary_daily_per30m where\n\tfitur = @fitur and is_success = @is_success  and isocode =  @isocode\n\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_amount)  num from PROSWITCHING.dbo.atm_transaction_summary_daily_H1\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\tgroup by trx_date,is_success\n\tunion all \n\tSELECT  trx_date,'ori_total_trx' metric, sum(total_amount)  num from PROSWITCHING.dbo.atm_transaction_realtime_grouping\n\twhere  fitur = @fitur and is_success = @is_success and  isocode =  @isocode\n\tgroup by trx_date,is_success\n\t),\n\tpred_total_trx as (\n\t\tSELECT  trx_date,'pred_total_trx' metric, sum(total_amount)  num FROM PROSWITCHING.dbo.atm_transaction_predict_new where\n\t\tfitur = @fitur and is_success = @is_success and isocode =  @isocode\n\t\tand DATEDIFF(day,trx_date,getdate()) <= @backdate_days_interval\n\t\tand DATEDIFF(MINUTE,trx_date,@max_date) > 0\n\t\tgroup by trx_date,is_success\n\t), combine as (\n select  DATEADD(HOUR, -7, trx_date) trx_date,metric, \n    -- Filter nilai negatif menjadi 0\n    CASE \n        WHEN num < 0 THEN 0 \n        ELSE num \n    END AS num\n    from ori_total_trx\n    union all \n    select DATEADD(HOUR, -7, trx_date) trx_date,metric, \n    -- Filter nilai negatif menjadi 0\n    CASE \n        WHEN num < 0 THEN 0 \n        ELSE num \n    END AS num\n    from pred_total_trx\n    )\n    select trx_date as time, metric, num from combine\n    where num > 0\n    order by trx_date,metric\nEND \n\n"
    }
   ]
  }
 ]
}